import BandeauDefiActif from '../components/BandeauDefiActif';
import SaisieDefisDynamiques from '../components/SaisieDefisDynamiques';

import React, { useEffect, useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import { defisReferentiel } from '../lib/defisReferentiel';
import { DEFIS_STATUS, getDefiMax, isDefiDisponible, isDefiEnCours, isDefiTermine } from '../lib/defisUtils';
import { initDefisUser } from '../lib/initDefisUser';
import { useRouter } from '../node_modules/next/router';
import { useDefis } from '../components/DefisContext';

function RetourArriere() {
    return <div style={{ margin:'2rem 0 1.5rem', textAlign:'center' }}><button onClick={() => window.history.back()} style={{background:'#1976d2',color:'#fff',border:'none',borderRadius:8,padding:'10px 28px',fontWeight:700,fontSize:17,cursor:'pointer'}}>← Retour</button></div>;
}

const Defis = () => {
    const [defis,setDefis]=useState([]); const router=useRouter(); const {refreshDefis}=useDefis();
    const [loading,setLoading]=useState(true); const [error,setError]=useState(null); const [tab,setTab]=useState('disponibles'); const [actionLoading,setActionLoading]=useState(false); const [userId,setUserId]=useState(null);
    const loadDefis=async()=>{setLoading(true);setError(null);try{const{data:authData,error:authError}=await supabase.auth.getUser();const uid=authData?.user?.id;if(authError||!uid){setUserId(null);setDefis([]);setError('Utilisateur non authentifié');return;}setUserId(uid);const initResult=await initDefisUser();if(initResult?.errors?.length)console.warn('Initialisation défis partielle:',initResult.errors);let{data,error:loadError}=await supabase.from('defis').select('*').eq('user_id',uid);if(loadError)throw loadError;for(const defi of data||[]){const ref=defisReferentiel.find(d=>d.description===defi.description);const normalisations={};if(ref&&defi.nom!==ref.nom)normalisations.nom=ref.nom;if(defi.status==='en attente')normalisations.status=DEFIS_STATUS.DISPONIBLE;if(Object.keys(normalisations).length){await supabase.from('defis').update(normalisations).eq('id',defi.id).eq('user_id',uid);}}const{data:finalData,error:finalError}=await supabase.from('defis').select('*').eq('user_id',uid);if(finalError)throw finalError;setDefis(finalData||[]);}catch(err){console.error(err);setError('Erreur lors du chargement des défis');}finally{setLoading(false);}};
    const synchroniserDefis=async()=>Promise.all([loadDefis(),refreshDefis()]); useEffect(()=>{loadDefis();},[]);
    const handleReinitialiserDefi=async(defi)=>{if(!userId)return;setActionLoading(defi.id);const{error}=await supabase.from('defis').update({progress:0,status:DEFIS_STATUS.DISPONIBLE}).eq('id',defi.id).eq('user_id',userId);if(error)setError('Erreur lors de la réinitialisation du défi');else await synchroniserDefis();setActionLoading(false);};
    const handleSupprimerDefi=async(id)=>{if(!userId||!window.confirm('Voulez-vous vraiment supprimer ce défi personnalisé ?'))return;setActionLoading(id);const{error}=await supabase.from('defis').delete().eq('id',id).eq('user_id',userId);if(error)setError('Erreur lors de la suppression du défi');else{await synchroniserDefis();alert('✅ Défi supprimé avec succès !');}setActionLoading(false);};
    const handleCommencerDefi=async(id)=>{if(!userId)return;setActionLoading(id);const defi=defis.find(d=>d.id===id);if(!defi){setError('Défi introuvable');setActionLoading(false);return;}const autres=defis.filter(d=>d.id!==id&&d.status===DEFIS_STATUS.EN_COURS);if(autres.length){const ok=window.confirm(`Tu as déjà le défi « ${autres[0].nom} » en cours. Commencer « ${defi.nom} » mettra ton défi actuel en pause et le replacera dans les défis disponibles. Continuer ?`);if(!ok){setActionLoading(false);return;}const ids=autres.map(d=>d.id);const{error:pauseError}=await supabase.from('defis').update({status:DEFIS_STATUS.DISPONIBLE}).in('id',ids).eq('user_id',userId);if(pauseError){setError('Impossible de mettre le défi actuel en pause');setActionLoading(false);return;}}
      const{error:updateError}=await supabase.from('defis').update({progress:0,status:DEFIS_STATUS.EN_COURS}).eq('id',id).eq('user_id',userId);if(updateError){setError('Erreur lors du démarrage du défi');setActionLoading(false);return;}await synchroniserDefis();setActionLoading(false);const perso=defi.type==='personnalise'||defi.type==='alimentaire'||!defisReferentiel.find(d=>d.description===defi.description);if(perso)router.push(`/journal-defi/${id}`);};
    const handleAccomplirEtape=async(defi)=>{setActionLoading(defi.id);const{validerEtapeDefi}=await import('../lib/defisUtils');const res=await validerEtapeDefi(defi);if(!res.success)setError(res.error||'Erreur lors de la progression du défi');else await synchroniserDefis();setActionLoading(false);};
    if(loading)return <div>Chargement des défis...</div>; if(error)return <div style={{color:'red'}}>{error}</div>;
    const disponibles=defis.filter(isDefiDisponible), encours=defis.filter(isDefiEnCours), termines=defis.filter(isDefiTermine), actif=encours[0]||null;
    const tabs=[['disponibles','Défis disponibles'],['en-cours','Défis en cours'],['termines','Défis terminés'],['creer','Créer un défi']];
    const card=(defi,mode)=>{const max=getDefiMax(defi);const perso=defi.type==='personnalise'||defi.type==='alimentaire'||!defisReferentiel.find(d=>d.description===defi.description);return <li key={defi.id} style={{marginBottom:20,border:'1px solid #eee',borderRadius:10,padding:20,background:mode==='termine'?'#e0ffe0':'#fff'}}><h2 style={{margin:0,fontSize:21}}>{defi.nom}</h2><div style={{margin:'8px 0',color:'#555'}}>{defi.description}</div><div>Progression : {defi.progress||0} / {max}</div>{mode==='disponible'&&<><button onClick={()=>handleCommencerDefi(defi.id)} disabled={!!actionLoading} style={{marginTop:10,padding:'8px 20px',border:0,borderRadius:8,background:'#1976d2',color:'#fff',fontWeight:700}}>Commencer ce défi</button>{perso&&<button onClick={()=>handleSupprimerDefi(defi.id)} style={{marginLeft:10,padding:'8px 16px',border:0,borderRadius:8,background:'#d32f2f',color:'#fff'}}>🗑️ Supprimer</button>}</>}{mode==='encours'&&<>{perso?<button onClick={()=>router.push('/journal-defi/'+defi.id)} style={{marginTop:10,padding:'7px 16px',border:0,borderRadius:6,background:'#9c27b0',color:'#fff'}}>📔 Ouvrir le journal</button>:<button onClick={()=>handleAccomplirEtape(defi)} style={{marginTop:10,padding:'7px 16px',border:0,borderRadius:6,background:'#80cbc4'}}>J'ai accompli une étape</button>}<button onClick={()=>handleReinitialiserDefi(defi)} style={{marginLeft:10,padding:'7px 16px',border:0,borderRadius:6,background:'#e57373',color:'#fff'}}>Réinitialiser</button></>}{mode==='termine'&&<div style={{color:'#388e3c',marginTop:10}}>🎉 Défi complété ! Bravo !</div>}</li>};
    return <div>{actif&&<BandeauDefiActif/>}<RetourArriere/><h1>Mes défis</h1><div style={{display:'flex',gap:16,marginBottom:24}}>{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{padding:'8px 24px',borderRadius:8,border:tab===id?'2px solid #1976d2':'1px solid #ccc',background:tab===id?'#e3f2fd':'#fff',fontWeight:tab===id?700:400}}>{label}</button>)}</div>{tab==='disponibles'&&<><p>Défis que tu peux commencer à tout moment.</p><ul style={{listStyle:'none',padding:0}}>{disponibles.length?disponibles.map(d=>card(d,'disponible')):<li>Aucun défi disponible.</li>}</ul></>}{tab==='en-cours'&&<><p>Voici ton défi actif.</p><ul style={{listStyle:'none',padding:0}}>{encours.length?encours.map(d=>card(d,'encours')):<li>Aucun défi en cours.</li>}</ul></>}{tab==='termines'&&<><p>Bravo pour ces défis terminés !</p><ul style={{listStyle:'none',padding:0}}>{termines.length?termines.map(d=>card(d,'termine')):<li>Aucun défi terminé.</li>}</ul></>}{tab==='creer'&&<><p>Créez vos propres défis personnalisés et suivez-les au quotidien.</p><SaisieDefisDynamiques refreshDefis={synchroniserDefis}/></>}</div>;
};
export default Defis;
