create table if not exists public.defis_observations_duree (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  defi_id integer not null references public.defis(id) on delete cascade,
  preuve_id text not null,
  reponse text not null,
  donnees jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint defis_observations_duree_reponse_check check (reponse in ('oui','non','autre')),
  constraint defis_observations_duree_unique unique (user_id, defi_id, preuve_id)
);

alter table public.defis_observations_duree enable row level security;

grant select, insert, update on public.defis_observations_duree to authenticated;
grant usage, select on sequence public.defis_observations_duree_id_seq to authenticated;

create policy "defis_observations_duree_select_owner"
on public.defis_observations_duree for select to authenticated
using ((select auth.uid()) = user_id);

create policy "defis_observations_duree_insert_owner"
on public.defis_observations_duree for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.defis d
    where d.id = defi_id and d.user_id = (select auth.uid())
  )
);

create policy "defis_observations_duree_update_owner"
on public.defis_observations_duree for update to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.defis d
    where d.id = defi_id and d.user_id = (select auth.uid())
  )
);
